---
- name: refresh pacman cache
  pacman:
    update_cache: yes
    
- name: install pacman packages
  pacman:
    name: "{{ ansible-arch-inxi.install }}"
    state: present
  when: ansible-arch-inxi.install is defined and (ansible-arch-inxi.install | length > 0)