---
- name: refresh pacman cache
  pacman:
    update_cache: yes
    
- name: install pacman packages
  pacman:
    name: "{{ ansible_arch_pacman.install }}"
    state: present
  when: ansible_arch_pacman.install is defined and (ansible_arch_pacman.install | length > 0)